/**
 * Date              Author           Des
 *----------------------------------------------
 * 2021-3-22           庞颖       axios的封装和拦截器
 * */

import {
  Button,
  Input,
  Select,
  Radio,
  Checkbox,
  DatePicker,
  TimePicker,
  Rate,
  Upload,
  Breadcrumb,
  Table,
  Pagination,
  Icon,
  Form
} from 'ant-design-vue'
import GlobalInput from '../components/Input'




let VueTransformNameList=[
  {
    name:'HSButton',
    component:Button
  },
  {
    name:'HSInput',
    component:Input
  },
  {
    name:'HSInputGroup',
    component:Input.Group
  },
  {
    name:'HSInputPassword',
    component:Input.Password
  },
  {
    name:'HSInputSearch',
    component:Input.Search
  },
  {
    name:'HSInputTextArea',
    component:Input.TextArea
  },
  {
    name:'HSelect',
    component:Select
  },
  {
    name:'HSelectGroup',
    component:Select.OptGroup
  },
  {
    name:'HSelectOption',
    component:Select.Option
  },
  {
    name:'HSRadio',
    component:Radio
  },
  {
    name:'HSRadioGroup',
    component:Radio.Group
  },
  {
    name:'HSRadioButton',
    component:Radio.Button
  },
  {
    name:'HSRadioGroup',
    component:Radio.Group
  },
  {
    name:'HSCheckBox',
    component:Checkbox
  },
  {
    name:'HSCheckboxGroup',
    component:Checkbox.Group
  },
  {
    name:'HSMonthPicker',
    component:DatePicker.MonthPicker
  },
  {
    name:'HSRangePicker',
    component:DatePicker.RangePicker
  },
  {
    name:'HSWeekPicker',
    component:DatePicker.WeekPicker
  },
  {
    name:'HSTimePicker',
    component:TimePicker
  },
  {
    name:'HSRate',
    component:Rate
  },
  {
    name:'HSUpload',
    component:Upload
  },
  {
    name:'HSBreadcrumb',
    component:Breadcrumb
  },
  {
    name:'HSBreadcrumbItem',
    component:Breadcrumb.Item
  },
  {
    name:'HSBreadcrumbSeparator',
    component:Breadcrumb.Separator
  },
  {
    name:'HSTable',
    component:Table
  },
  {
    name:'HSIcon',
    component:Icon
  },
  {
    name:'HSPagination',
    component:Pagination
  },
  {
    name:'HSForm',
    component:Form
  },
  {
    name:GlobalInput.name,
    component:GlobalInput
  }
  ]
export const transformComponent=(tempVue)=>{
  VueTransformNameList.map(item=>{
    tempVue.component(item.name,item.component)
  })
}
